import os
import subprocess

def create_file(path, content=''):
    """Create a file with the given content."""
    with open(path, 'w') as file:
        file.write(content)

def create_gitignore():
    """Create the .gitignore file."""
    gitignore_content = """
# Dependency directories
node_modules/
venv/
env/
ENV/
env.bak/
ENV.bak/

# pycache
temapltes/__pycache__/
defaults/__pycache__/
__pycache__/

# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like Istanbul
coverage

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# Jekyll metadata directory (https://jekyllrb.com/)
_site

# dotenv environment variable files
.env
.env.test
.env*.local

# Debug log from npm
npm-debug.log*

# Build files
build/
dist/

# TypeScript cache
*.tsbuildinfo

# IDE and editor folders
.idea/
.vscode/
*.swp
*.swo
*.sublime-workspace
*.sublime-project

# OS generated files
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db
    """
    create_file('.gitignore', gitignore_content)
    # print(".gitignore created successfully.")

if __name__ == "__main__":
    create_gitignore()
